#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re

def translate_item(小項目, prompt):
    """英語項目を日本語に翻訳"""
    
    # 翻訳辞書
    translation_dict = {
        # 基本動詞・形容詞
        'clear liquid': '透明な液体',
        'airy': '風通しの良い',
        'hair censor': '髪で隠す',
        'visible air': '見える空気',
        'chart': 'チャート',
        'interface': 'インターフェース',
        'cup': 'カップ',
        'sheets': 'シーツ',
        'blanket': '毛布',
        'iphone': 'iPhone',
        'youtube screen': 'YouTube画面',
        'cross-section': '断面図',
        'xray': 'X線',
        'cheating': '浮気',
        'netorare': '寝取られ',
        'neto': '寝取',
        'peeking out': '覗き見',
        'public stubble': '陰毛の剃り跡',
        'business card': '名刺',
        'scifi': 'SF',
        'touhou theme': '東方テーマ',
        
        # 人名・キャラクター
        'azki (hololive)': 'AZKi',
        'klonoa': 'クロノア',
        'venus': 'ヴィーナス',
        'meowfficer_(azur_lane)': 'ミャーフィサー',
        'anira': 'アニラ',
        
        # 作家・アーティスト名
        'style of anmi': 'Anmi風',
        'bkub': 'BKUB',
        'bunbun': 'BUNBUN',
        'cho theg': 'Cho theg',
        'illustrated by(null_(nyanpyoun))': 'NULL作画',
        'tony_taka': 'Tony Taka',
        'abmayo': 'abmayo',
        'adoohay': 'adoohay',
        'amane hasuhito': '天音はすひと',
        'asdkd123': 'asdkd123',
        'bulga': 'bulga',
        'dolphin wave': 'ドルフィンウェーブ',
        'fumihiko (fu mihi ko)': 'ふみひこ',
        'nanashi(nlo)': 'nanashi',
        'sy4': 'sy4',
        
        # 技術用語
        'sns': 'SNS',
        'asus': 'ASUS',
        'basquet': 'バスケット',
        'basketball': 'バスケットボール',
        'eju': '日本語教育',
        'educ': '教育',
        'education': '教育',
        
        # 動作・ポーズ
        'stand': '立つ',
        'standing': '立っている',
        'bend': '曲げる',
        'bending': '曲がる',
        'lean': 'もたれる',
        'lean back': '後ろに寄りかかる',
        'looking': '見ている',
        'facing': '向いている',
        'facing to the side': '横向き',
        'face to face': '向かい合う',
        'tilt head': '首をかしげる',
        'head tilt': '首をかしげる',
        'cross arm': '腕組み',
        'arms crossed': '腕組み',
        'spreading arms': '腕を広げる',
        'hands crossed': '手を交差',
        'arms_at_sides': '腕を体側に',
        'bowlegged pose': 'がに股ポーズ',
        'upright straddle': '直立またがり',
        'squatting_cowgirl_position': 'しゃがみ騎乗位',
        'figure four sitting': '片膝立て座り',
        'mating press': 'マッティングプレス',
        'pile-driver': 'パイルドライバー',
        'stradding': 'またがり',
        'straggle': 'もがく',
        'struggle': '抵抗',
        'stragg': 'もがき',
        
        # 身体・解剖学
        'belly button': 'へそ',
        'areola': '乳輪',
        'areolae': '乳輪',
        'nipple': '乳首',
        'nipple line': '乳首のライン',
        'nipple tweak': '乳首をつまむ',
        'sucking nipples': '乳首を吸う',
        'nipple sucking': '乳首吸い',
        'nipple licking': '乳首舐め',
        'show off nipples': '乳首を見せつける',
        'breast out': '胸を出す',
        'breast shaking': '胸の揺れ',
        'shaking breasts': '揺れる胸',
        'breasts shade': '胸の影',
        'huge areolae': '巨大乳輪',
        'erectile': '勃起した',
        'flat chest': '貧乳',
        'medium chest': '中くらいの胸',
        'sexy cleavage': 'セクシーな谷間',
        'cleavage': '谷間',
        'palm': '手のひら',
        'fingernails': '爪',
        'spine': '背骨',
        'back muscles': '背筋',
        'nape': 'うなじ',
        'waist': '腰',
        'skin': '肌',
        'body hair': '体毛',
        'canine': '犬歯',
        'teeth': '歯',
        'lips': '唇',
        'eye': '目',
        'cat-like eyes': '猫のような目',
        'catlike eyes': '猫のような目',
        'teary-eyed': '涙目',
        'tear bags': '涙袋',
        'tear streaks': '涙の筋',
        'puffy cheeks': '膨らんだ頬',
        'cheeks': '頬',
        'corners of mouth': '口角',
        'corner of mouth': '口角',
        'uvula': 'のどちんこ',
        'sideburns': 'もみあげ',
        'hair combing': '髪を梳く',
        'hair loss': '抜け毛',
        'hair complex': '複雑な髪',
        'hair volume': '毛量',
        'soft and fluffy': 'ゆるふわ',
        'three-stranded': '三つ編み',
        'bunny ears': 'うさ耳',
        'fox tail': '狐の尻尾',
        'one tail': '1本の尻尾',
        'kemomimi': 'ケモ耳',
        
        # 表情・感情
        'shy': '恥ずかしがり',
        'shy laugh': '照れ笑い',
        'embarrassed': '恥ずかしい',
        'embarrassing': '恥ずかしい',
        'crying': '泣いている',
        'crying face': '泣き顔',
        'sobbing': 'すすり泣き',
        'disappointed': 'がっかり',
        'shocked': 'ショック',
        'regrettable': '悔しい',
        'regret': '後悔',
        'disgust': '嫌悪',
        'dissatisfaction': '不満',
        'jealous': '嫉妬深い',
        'anxiety': '不安',
        'panic': 'パニック',
        'surprise': '驚き',
        'intense': '激しい',
        'passionate': '情熱的',
        'passion': '情熱',
        'ecstasy': '恍惚',
        'climax': '絶頂',
        'orgasm': 'オーガズム',
        'gasping': 'あえぎ',
        'sexy': 'セクシー',
        'drunk': '酔っ払い',
        'dead drunk': '泥酔',
        'quietly': '静かに',
        'spicy': '辛い',
        'love': '愛',
        'love love': 'ラブラブ',
        'i love you': '大好き',
        'welcome': 'ようこそ',
        'perfection': '完璧',
        'perfect': '完璧',
        'real': '本物',
        'same': '同じ',
        'identical': '同一',
        'different': '違う',
        'careful': '慎重',
        'concentration': '集中',
        'fatal': '致命的',
        'deadly': '死に至る',
        'exhaustion': '疲労',
        'tired': '疲れた',
        
        # 服装・衣類
        'dress shirt': 'ワイシャツ',
        'running shirt': 'ランニングシャツ',
        'shirt hem': 'シャツの裾',
        'shirt pull': 'シャツを引っ張る',
        'topless': 'トップレス',
        'bodycon': 'ボディコン',
        'cami': 'キャミソール',
        'gown': 'ガウン',
        'apron': 'エプロン',
        'corset': 'コルセット',
        'high neck': 'ハイネック',
        'stomach band': '腹巻き',
        'arm covers': 'アームカバー',
        'face veil': 'フェイスベール',
        'chin mask': '顎マスク',
        'front hook': 'フロントホック',
        'loose bra': 'ゆるいブラ',
        'bra peek': 'ブラチラ',
        'knee socks': 'ニーソックス',
        'striped pants': '縞パン',
        'no underwear': 'ノーパン',
        'panty shot': 'パンティーショット',
        'panty': 'パンティー',
        'crotchless': 'クロッチレス',
        'panty gag': 'パンティーギャグ',
        'panty line': 'パンティーライン',
        'in underwear': '下着姿',
        'hot pants': 'ホットパンツ',
        'loafers': 'ローファー',
        'cowboy boots': 'カウボーイブーツ',
        'sandals': 'サンダル',
        'indoor shoes': '上履き',
        'tabi': '足袋',
        'heel': 'ヒール',
        'heels': 'ヒール',
        'shoe box': '下駄箱',
        'bunny': 'バニー',
        'loincloth': '褌',
        'half-covered': '半被',
        'armor': '甲冑',
        'military lolita': 'ミリタリーロリータ',
        'slingshot': 'スリングショット',
        'bondage outfit': 'ボンデージ衣装',
        'tribalwear': '部族衣装',
        'wearing clothes': '服を着ている',
        'clothed female': '女性着衣',
        'casual wear': '普段着',
        'disheveled clothes': '乱れた服',
        'completely naked': '全裸',
        'naked': '裸',
        'nude': 'ヌード',
        'fully exposed': '丸出し',
        'exposure': '露出',
        'exposed': '露出した',
        'exposing': '晒し',
        'shoulder bare': '肩出し',
        
        # 色・材質・質感
        'highlights': 'ハイライト',
        'contrast': 'コントラスト',
        'whitening': '美白',
        'grain': '木目',
        'satin': 'サテン',
        'rubber': 'ラバー',
        'enamel': 'エナメル',
        'mesh': 'メッシュ',
        'vinyl': 'ビニール',
        'concrete': 'コンクリート',
        'textile': 'テキスタイル',
        'thick': '厚い',
        'thin': '薄い',
        'lost weight': '痩せた',
        'half': '半分',
        'monochromatic': '単色',
        'black paint': '黒塗り',
        'black line': '黒線',
        'black belt': '黒帯',
        'black tights': '黒タイツ',
        'tight': 'タイト',
        'see-through': '透け',
        'transparent': '透明',
        'leopard print': 'ヒョウ柄',
        'panther_print': 'パンサープリント',
        'polka dots cotton panties': '水玉模様のコットンパンティー',
        'plaid': 'チェック柄',
        
        # 場所・環境
        'coffee shop': '喫茶店',
        'university': '大学',
        'in front of the store': '店の前',
        'clerk': '店員',
        'shop': '店',
        'dance hall': 'ダンスホール',
        'camp': 'キャンプ',
        'fair': '縁日',
        'baseball': '野球',
        'ballet': 'バレエ',
        'business': 'ビジネス',
        'racetrack': 'レース場',
        'school swimming pool': '学校のプール',
        'on the train': '電車の中',
        'train seats': '電車の座席',
        'train seat': '電車のシート',
        'dojo': '道場',
        'cave': '洞窟',
        'western-style room': '洋室',
        'japanese-style room': '和室',
        'toilet': '便器',
        'western-style toilet': '洋式便器',
        'japanese style toilet bowl': '和式便器',
        'large communal bath': '大浴場',
        'soak in the bath': 'お風呂に浸かる',
        'take a bath': 'お風呂に入る',
        'bath': 'バス',
        'open-air bath': '露天風呂',
        'shower room': 'シャワールーム',
        'basement': '地下室',
        'stone floor': '石の床',
        'mirror floor': '鏡張りの床',
        'ground': '地面',
        'on the ground': '地面に',
        'waterfront': '水辺',
        'seaside': '海辺',
        'immerse in water': '水に浸かる',
        'water up to one\'s chest': '胸まで水に浸かる',
        'pour water on': '水をかける',
        'fitting room': 'フィッティングルーム',
        'sliding door': '引き戸',
        'supermarket bag': 'スーパーの袋',
        'plastic bags': 'ビニール袋',
        'alley': '路地',
        'back alley': '裏路地',
        'on the wall': '壁に',
        'on wall': '壁に',
        'put your hands on the wall': '壁に手をつく',
        'against glass': 'ガラス越し',
        'through': '通して',
        'around': '周り',
        'partially underwater': '部分的に水中',
        'underwater': '水中',
        
        # オブジェクト・道具
        'microphone stand': 'マイクスタンド',
        'vacuum cleaner': '掃除機',
        'dust cloth': '雑巾',
        'bath towels': 'バスタオル',
        'tablecloths': 'テーブルクロス',
        'straps': 'つり革',
        'broom': '箒',
        'tea': 'お茶',
        'whales': 'クジラ',
        'rabbit': 'ウサギ',
        'bear': 'クマ',
        'fox': '狐',
        'puppy': '子犬',
        'insect': '昆虫',
        'twins': '双子',
        'beast': '獣',
        'sunburn': '日焼け',
        'sunset': '夕焼け',
        'red sun': '真っ赤な太陽',
        'contrail': '飛行機雲',
        'sea ​​of ​​clouds': '雲海',
        'late night': '深夜',
        'noon': 'お昼',
        'air': '空気',
        'seed': '種',
        'buried': '埋まった',
        'bury': '埋める',
        'hug': '抱擁',
        'layers': 'レイヤー',
        'layer': '層',
        'dull': 'くすんだ',
        'crab': 'カニ',
        'cyclops': 'サイクロプス',
        'from back': '後ろから',
        'collapse': '崩壊',
        'penis awe': 'ペニス崇拝',
        'basket': 'バスケット',
        'basketball': 'バスケットボール',
        'living': '生きている',
        'alive': '生きた',
        'dutch': 'オランダ語',
        
        # 動作・行為
        'tossing someone up in the air': '胴上げ',
        'bear': '背負う',
        'carry a bag': '鞄を背負う',
        'climbing the stairs': '階段を上る',
        'mopping': '雑巾がけ',
        'mopping the floor': '床を拭く',
        'wipe': '拭く',
        'bite': '噛む',
        'biting': '噛む',
        'hold a cigarette in your mouth': '煙草をくわえる',
        'smoking': '喫煙',
        'eat': '食べる',
        'vomit': '吐く',
        'asleep': '眠っている',
        'sleeping': '寝ている',
        'sleeping together': '添い寝',
        'pray': '祈る',
        'playing': '遊んでいる',
        'play': '遊ぶ',
        'tickle': 'くすぐる',
        'petting': 'なでる',
        'pet': 'ペット',
        'scoop with hands': '手ですくう',
        'smelling': '匂いを嗅ぐ',
        'fall down': '倒れる',
        'fold': '畳む',
        'scribble': '落書き',
        'scattering': '散乱',
        'scatter': 'ちらばる',
        'collapsed': '潰れた',
        'swelling': '腫れ',
        'bounce': '弾む',
        'wrap around': '巻きつく',
        'extend': '伸ばす',
        'flaccid': '弛緩した',
        'tweak': '微調整',
        'recording': '録画',
        'delivery': '配信',
        'streaming': 'ストリーミング',
        'censorship': '検閲',
        'proof': '証明',
        'maintenance': '整備',
        'temptation': '誘惑',
        'taunt': '挑発',
        'assistance': '援助',
        'job type': '職種',
        'victory': '勝利',
        'villain': '悪党',
        'atmosphere': '雰囲気',
        'marriage': '結婚',
        'wedding': '結婚式',
        'wedding ceremony': '結婚式',
        'god': '神',
        'legend': '伝説',
        'scenery': '景色',
        'view': '眺め',
        'rank': 'ランク',
        'top': '上位',
        'rear': '後ろ',
        'behind': '後ろに',
        'in front': '前で',
        'near': '近く',
        'distance': '距離',
        'direction': '方向',
        'leave': '離れる',
        'annex': '離れ',
        'departed': '離れた',
        'hand over': '渡す',
        'secretly': 'こっそり',
        'twist': 'ひねる',
        'posture': '姿勢',
        'age': '年齢',
        'age gap': '年の差',
        'junior': 'ジュニア',
        'baby': '赤ちゃん',
        'child': '子供',
        'children': '子供たち',
        'adult': '大人',
        'adult women': '大人の女性',
        'cling': 'しがみつく',
        'blown away': '吹き飛ばされる',
        'to be blown away': '飛ばされる',
        'defeated': '敗北した',
        'retrograde': '逆行',
        'hide the meaning': '意味を隠す',
        'invite': '招く',
        'invitation': '招待',
        'inhale': '吸う',
        'kabedon': '壁ドン',
        'two shots': 'ツーショット',
        'last minute': '直前',
        'imminent': '差し迫った',
        'ambiguous': '曖昧',
        'upside-down': '逆さま',
        'backlit': '逆光',
        'backlighting': '逆光照明',
        'invisible air': '見えない空気',
        'clear liquid': '透明な液体',
        'airy': '風通しの良い',
        'fantasy': 'ファンタジー',
        'imagination': '想像',
        'decadent': '退廃的',
        'decadence': '退廃',
        'vulgar': '下品',
        'obscene': 'わいせつ',
        'static': '静止した',
        'still': '静止',
        
        # 成人向け
        'restraint': '拘束',
        'bondage': 'ボンデージ',
        'handcuffs': '手錠',
        'big cock': '巨根',
        'erection': '勃起',
        'phimosis': '包茎',
        'foreskin': '包皮',
        'foreskin penis': '包茎ペニス',
        'scrotum': '陰嚢',
        'balls': '睾丸',
        'penis': 'ペニス',
        'cock': 'ペニス',
        'dick': 'ペニス',
        'urethra': '尿道',
        'urethra attack': '尿道攻め',
        'semen': '精液',
        'cum': '精液',
        'ejaculation': '射精',
        'firing': '発射',
        'facial ejaculation': '顔面射精',
        'facial': '顔射',
        'internal cumshot': '中出し',
        'cum in mouth': '口内射精',
        'cum in headwear': '帽子内射精',
        'cum overflow': '精液溢れ',
        'excessive cum': '大量射精',
        'cum on mouth': '口に精液',
        'cream pie': 'クリームパイ',
        'grab your ass': 'お尻を掴む',
        'anal hole': '肛門',
        'anal insertion': 'アナル挿入',
        'anal plug': 'アナルプラグ',
        'anal pearls': 'アナルパール',
        'anal beads': 'アナルビーズ',
        'anal hook': 'アナルフック',
        'red butt': '赤いお尻',
        'buttocks': '臀部',
        'ass': 'お尻',
        'butt': 'お尻',
        'blowjob': 'フェラチオ',
        'fellatio': 'フェラチオ',
        'deepthroat': 'ディープスロート',
        'oral': 'オーラル',
        'lick': '舐める',
        'licking': '舐める',
        'licking one\'s lips': '唇を舐める',
        'tongue': '舌',
        'out tongue': '舌出し',
        'spread that place': 'あそこを広げる',
        'crack': '割れ目',
        'slit': 'スリット',
        'pussy': 'マンコ',
        'vagina': '膣',
        'hymen': '処女膜',
        'breaking the hymen': '処女膜破り',
        'virgin': '処女',
        'cervix': '子宮頸部',
        'clitoris': 'クリトリス',
        'clitoris piercing': 'クリトリスピアス',
        'sweat dripping': '汗が滴る',
        'juice': '愛液',
        'mucus': '粘液',
        'mucous membrane': '粘膜',
        'slimy': 'ぬるぬる',
        'dripping': '滴る',
        'saliva lotion': '唾液ローション',
        'lotion': 'ローション',
        'spit': '唾',
        'saliva': '唾液',
        'drool': 'よだれ',
        'saliva_trail': '唾液の筋',
        'urine': '尿',
        'piss': '小便',
        'relieve yourself': '用を足す',
        'holy water': '聖水',
        'incontinence': '失禁',
        'poop': 'うんち',
        'feces': '糞尿',
        'vibe': 'バイブ',
        'vibrator': 'バイブレーター',
        'machine vibrator': 'マシンバイブ',
        'electric massager': '電マ',
        'onahole': 'オナホール',
        'sex toys': '大人のおもちゃ',
        'cock ring': 'コックリング',
        'packing tape': 'ガムテープ',
        'speculum': 'クスコ',
        'vacuum': 'バキューム',
        'condom': 'コンドーム',
        'climax': '絶頂',
        'orgasm': 'オーガズム',
        'ahegao': 'アヘ顔',
        'aphrodisiac': '媚薬',
        'dick cheese': 'チンカス',
        'someone else licks my nipples': '他人が乳首をなめる',
        'piston': 'ピストン',
        'mating press': 'マッティングプレス',
        'piledriver': 'パイルドライバー',
        'pile driver': 'パイルドライバー',
        'hip shaking': '腰振り',
        'push out your hips': '腰を突き出す',
        'grabbing': '掴む',
        'sex': 'セックス',
        'sexual': '性的',
        'intercourse': '性交',
        'penetration': '挿入',
        'insert': '挿入する',
        'insertion': '挿入',
        'deep_penetration': '深い挿入',
        'imminent penetration': '挿入直前',
        'penetrate': '貫通する',
        'covered penetration': '覆われた貫通',
        'through wall': '壁越し',
        'masturbation': 'オナニー',
        'self': 'セルフ',
        'death rape': '死姦',
        'necrophilia': 'ネクロフィリア',
        'abduction': '拉致',
        'bullying': 'いじめ',
        'violence': '暴力',
        'molester': '痴漢',
        'voyeur': '盗撮',
        'peeping': '覗き',
        'lesbian': 'レズビアン',
        'yuri': '百合',
        'fallen into evil': '悪堕ち',
        'falling bad': '悪落ち',
        'brainwashing': '洗脳',
        'stethoscope': '聴診器',
        'physical build': '体格',
        'height': '身長',
        'love hotel': 'ラブホテル',
        
        # 品質・技術
        'nsfw': 'NSFW',
        'masterpiece': '傑作',
        'master piece': '傑作',
        'master': 'マスター',
        'best quality': '最高品質',
        'high quality': '高品質',
        'official': '公式',
        'highly detailed': '高詳細',
        'detailed': '詳細',
        'ultra-detailed': '超詳細',
        'perfect': '完璧',
        'amazing': '素晴らしい',
        'aesthetic': '美的',
        'very aesthetic': '非常に美的',
        'intricate': '複雑',
        'depth of field': '被写界深度',
        'motion lines': 'モーションライン',
        'uncensored': '無修正',
        'explicit': '明示的',
        'score': 'スコア',
        'copyright': '著作権',
        'x-ray': 'X線',
        'projection': '投影',
        'structure': '構造',
        'cut-in': 'カットイン',
        'noise': 'ノイズ',
        'minimal background': 'ミニマル背景',
        'pillarboxed': 'ピラーボックス',
        'viewer': 'ビューワー',
        'interface': 'インターフェース',
        
        # その他の複雑な表現
        'come hither': 'おいで',
        'rocket': 'ロケット',
        'internal cumshot': '中出し',
        'facing': '向いている',
        'atmosphere': '雰囲気',
        'petting': 'なでる',
        'pressed': '押された',
        'sound effects': '効果音',
        'firefly': 'ホタル',
        'star rail': 'スターレイル',
        'loss': '敗北',
        'alternate costume': '別衣装',
        'public stubble': '陰毛剃り跡',
        'hot': '熱い',
        'completely naked': '完全に裸',
        'command spell': '令呪',
        'constriction': '収縮',
        'racetrack': 'レース場',
        'seal': 'シール',
        'open arms forward': '前に腕を開く',
        'panty gag': 'パンティーギャグ',
        'dead drunk': '泥酔',
        'kabedon': '壁ドン',
        'loose bra': 'ゆるいブラ',
        'crotchless': 'クロッチレス',
        'maintenance': 'メンテナンス',
        'hands between legs': '股間に手',
        'jealous': '嫉妬深い',
        'the idolmaster': 'アイドルマスター',
        'hair censor': '髪で隠す',
        'white people': '白人',
        'donation box': '募金箱',
        'pi piece': 'ピピース',
        'falling bad': '悪落ち',
        'arms on': '腕を乗せる',
        'parent and child': '親子',
        'shhhh': 'シーッ',
        'quietly': '静かに',
        'upright straddle': '直立またがり',
        'impose': '押し付ける',
        'turn away': '顔を背ける',
        'ultra': 'ウルトラ',
        'obscene': 'わいせつ',
        'backlit': '逆光',
        'back alley': '裏路地',
        'woman on a plate': '女体盛り',
        'female body': '女体',
        'tomboy': 'おてんば',
        'boyish': 'ボーイッシュ',
        'assistance': '援助',
        'on_side': '横向き',
        'femdom': '女王様',
        'insect': '昆虫',
        'biting': '噛む',
        'scoop with hands': '手ですくう',
        'plaid': 'チェック柄',
        'huge areolae': '巨大乳輪',
        'erectile': '勃起した',
        'breast out': '胸出し',
        'incredibly absurd': '信じられないほど不条理',
        'contrapposto': 'コントラポスト',
        'straggle': 'もがく',
        'struggle': 'もがく',
        'connection': '繋がり',
        'connect': '繋ぐ',
        'piss': '小便',
        'relieve yourself': '用を足す',
        'holy water': '聖水',
        'bondage outfit': 'ボンデージ衣装',
        'visible air': '見える空気',
        'around': '周囲',
        'sir': 'サー',
        'hand on mouth': '口に手',
        'contraction': '収縮',
        'facing to the side': '横向き',
        'projection': '投影',
        'adult': '大人',
        'side sleeping': '横向きで寝る',
        'sideways body': '横向きの体',
        'bend': '曲げる',
        'beach chairs': 'ビーチチェア',
        'bounce': '弾む',
        'public stubble,testicle': '陰毛剃り跡,睾丸',
        'bowlegged pose': 'がに股ポーズ',
        'cv': '履歴書',
        'arms_at_sides': '腕を体側に',
        'tea': 'お茶',
        'peeking out': '覗き見',
        'playing with hair': '髪をいじる',
        'peace sign': 'ピースサイン',
        'clear liquid': '透明な液体',
        'support': 'サポート',
        'bear': 'クマ',
        'oho': 'オホ',
        'sexy': 'セクシー',
        'drool': 'よだれ',
        'thick': '太い',
        'phimosis': '包茎',
        'foreskin': '包皮',
        'tickle': 'くすぐる',
        'scrotum': '陰嚢',
        'firing': '発射',
        'hair loss': '髪が抜ける',
        'petting': 'なでる',
        'wrap around': '巻きつく',
        'dull': 'くすんだ',
        'face close': '顔が近い',
        'facing each other': '向かい合う',
        'faint': '気絶',
        'weakness': '脱力',
        'endure': '堪える',
        'expression of endurance': '我慢の表情',
        'endure': '我慢する',
        'loss of consciousness': '意識を失う',
        'relax': '力を抜く',
        'eyeliner': 'アイライン',
        'spine': '背骨',
        'back muscles': '背筋',
        'nape': 'うなじ',
        'hands': '手',
        'condominium': 'コンドミニアム',
        'breathing': '呼吸',
        'rough': '荒い',
        'seeding': '種付け',
        'making': '作る',
        'faceplant': '顔面着地',
        'amazoness': 'アマゾネス',
        'i love you': '大好き',
        'warp': '反る',
        'mons public': '恥丘',
        'doujin cover': '同人誌表紙',
        'drooping': '垂れる',
        'crab claws': 'カニ挟み',
        'top': '上位',
        'nibbling': 'かじる',
        'plasticine': 'プラスチック',
        'same': '同じ',
        'high neck': 'ハイネック',
        'scowl': '顔をしかめる',
        'toriyama': '鳥山',
        'upskirt': 'アップスカート',
        'exessive': '過度',
        'exe': 'エグゼ',
        'attack': '攻撃',
        'climax y': '絶頂Y',
        'copyright': '著作権',
        'oil': 'オイル',
        'crit': 'クリティカル',
        'hyperemia': '充血',
        'balls': '玉',
        'dish': '皿',
        'single layer': '一重',
        'dismayed': '呆れ',
        'pupp': '子犬',
        'bath towels': 'バスタオル',
        'curtsey': 'カーテシー',
        'careful': '慎重',
        'clothed female': '着衣女性',
        'button': 'ボタン',
        'head tilt': '首傾げ',
        'figure four sitting': '四の字座り',
        'claw foot bathtub': '猫足バスタブ',
        'sucking nipples': '乳首を吸う',
        'shoe_soles': '靴底',
        'nipple line': '乳首のライン',
        'lean back': '後ろに寄りかかる',
        'lips': '唇',
        'near': '近い',
        'distance': '距離',
        'sandwich': 'サンドイッチ',
        'sand': '砂',
        'button gap': 'ボタンの隙間',
        'noise': 'ノイズ',
        'cross arm': '腕組み',
        'spreading arms': '腕を広げる',
        'through': '通して',
        'against glass': 'ガラス越し',
        'shaving': '剃毛',
        'full-harness made of rope': 'ロープ製フルハーネス',
        'pile-driver': 'パイルドライバー',
        'fitting room': 'フィッティングルーム',
        'chin mask': '顎マスク',
        'hands crossed': '手を交差',
        'covered penetration': '覆われた挿入',
        'holding_another\'s_wrist': '相手の手首を掴む',
        'shave head': '剃り上げる',
        'support': 'サポート',
        'stimulation': '刺激',
        'no pants on': 'パンツを履いていない',
        'see cut': '見切れ',
        'licking one\'s lips': '舌なめずり',
        'smelling': '匂いを嗅ぐ',
        'pillarboxed': 'ピラーボックス',
        'foreskin': '包皮',
        'foreskin penis': '包茎ペニス',
        'narrow': '狭い',
        'painful': '痛い',
        'pinching': 'つまむ',
        'tablecloths': 'テーブルクロス',
        'fall down': '倒れる',
        'structure': '構造',
        'lean back': '後ろに寄りかかる',
        'exhaustion': '疲労',
        'sled': 'そり',
        'satin': 'サテン',
        'manicure': 'マニキュア',
        'sexy pose': 'セクシーポーズ',
        'weaver girl': '織姫',
        'brainwashing': '洗脳',
        'broad shoulders': '広い肩',
        'wave hands': '手を振る',
        'imminent penetration': '挿入直前',
        'tohoku itako': '東北イタコ',
        'cheeks': '頬',
        'the most important thing': '絶対領域',
        'imminent penetration': '挿入直前',
        'aqueous': '水性',
        'be proud': '胸を張る',
        'blanket': '毛布',
        'cut-in': 'カットイン',
        'fleck': 'そばかす',
        'freck': 'そばかす',
        'breast shade': '胸の影',
        'minimal background': 'ミニマル背景',
        'vibe': 'バイブ',
        'insert': '挿入',
        'piping': 'パイピング',
        'swelling': '膨れ',
        'confrontation': '対峙',
        'rolled up': '巻き上げる',
        'partially underwater': '部分的に水中',
        'lean': 'もたれる',
        'two shots': 'ツーショット',
        'saliva_trail': '唾液の筋',
        'deep_penetration': '深い挿入',
        'squatting_cowgirl_position': 'しゃがみ騎乗位',
        'last minute': '直前',
        'ambiguous': '曖昧',
        'upside-down': '逆さま',
        'age': '年齢',
        'shaved': '剃毛',
        'cum on mouth,cream pie': '口に精液,クリームパイ',
        'crop_top_overhang': 'クロップトップはみ出し',
        'departed': '離れた',
        'hand over': '渡す',
        'secretly': 'こっそり',
        'shaft look': 'シャフト見',
        'fold': '畳む',
        'flaccid': '弛緩',
        'wearing': '着用',
        'wearing clothes': '服を着ている',
        
        # 追加の未分類項目
        'dishv': 'ディッシュ',
        'ranndoseru': 'ランドセル',
        'spokun': 'スポーク',
        'eju': '日本語教育',
        'basquet': 'バスケット',
        'business card': '名刺',
        'klonoa': 'クロノア',
        'venus': 'ヴィーナス',
        'meowfficer_(azur_lane)': 'ミャーフィサー',
        'anira': 'アニラ',
        'neto': '寝取',
        'netorare': '寝取られ',
        'cheating': '浮気',
        'pubic stubble': '陰毛剃り跡',
        'scifi': 'SF',
        'touhou theme': '東方テーマ',
        'style of anmi': 'Anmi風',
        'bkub': 'BKUB',
        'bunbun': 'BUNBUN',
        'cho theg': 'Cho theg',
        'illustrated by(null_(nyanpyoun))': 'NULL作画',
        'tony_taka': 'Tony Taka',
        'abmayo': 'abmayo',
        'adoohay': 'adoohay',
        'amane hasuhito': '天音はすひと',
        'asdkd123': 'asdkd123',
        'bulga': 'bulga',
        'dolphin wave': 'ドルフィンウェーブ',
        'fumihiko (fu mihi ko)': 'ふみひこ',
        'nanashi(nlo)': 'nanashi',
        'sy4': 'sy4',
    }
    
    # 小項目と prompt の翻訳
    translated_小項目 = translation_dict.get(小項目.lower(), 小項目)
    translated_prompt = translation_dict.get(prompt.lower(), prompt)
    
    # 大文字小文字を考慮した翻訳も試行
    if translated_小項目 == 小項目:
        translated_小項目 = translation_dict.get(小項目, 小項目)
    if translated_prompt == prompt:
        translated_prompt = translation_dict.get(prompt, prompt)
    
    return translated_小項目, translated_prompt

def main():
    try:
        # 英語項目ファイルを読み込み
        with open('english_items_to_translate.tsv', 'r', encoding='utf-8') as f:
            english_lines = f.readlines()
        
        # マスターデータを読み込み
        with open('マスターデータ.tsv', 'r', encoding='utf-8') as f:
            master_lines = f.readlines()
        
        # 翻訳マッピングを作成
        translation_map = {}
        
        for line in english_lines:
            line = line.strip()
            if not line:
                continue
                
            parts = line.split('\t')
            if len(parts) >= 4:
                大項目 = parts[0]
                中項目 = parts[1]
                小項目 = parts[2]
                prompt = parts[3]
                
                # 翻訳実行
                translated_小項目, translated_prompt = translate_item(小項目, prompt)
                
                if translated_小項目 != 小項目 or translated_prompt != prompt:
                    # 元の行をキーとして翻訳後の行を値として保存
                    new_line = f"{大項目}\t{中項目}\t{translated_小項目}\t{translated_prompt}"
                    translation_map[line] = new_line
                    print(f"翻訳: {小項目} -> {translated_小項目}")
                    if prompt != translated_prompt:
                        print(f"      {prompt} -> {translated_prompt}")
        
        print(f"\n翻訳対象項目: {len(translation_map)}個")
        
        # マスターデータを更新
        if translation_map:
            updated_lines = []
            for line in master_lines:
                line = line.strip()
                if line in translation_map:
                    updated_lines.append(translation_map[line] + '\n')
                else:
                    updated_lines.append(line + '\n')
            
            # バックアップ作成
            import datetime
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            backup_filename = f"backups/マスターデータ_before_translation_{timestamp}.tsv"
            
            with open('マスターデータ.tsv', 'r', encoding='utf-8') as f:
                backup_content = f.read()
            with open(backup_filename, 'w', encoding='utf-8') as f:
                f.write(backup_content)
            
            # 更新されたマスターデータを書き込み
            with open('マスターデータ.tsv', 'w', encoding='utf-8') as f:
                f.writelines(updated_lines)
            
            print(f"マスターデータを更新しました（バックアップ: {backup_filename}）")
        else:
            print("翻訳が必要な項目はありませんでした")
        
    except Exception as e:
        print(f"エラーが発生しました: {e}")

if __name__ == "__main__":
    main()